version: "3"

services:
  web:
    image: shdv/hat.sh
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_TURN_URL=${TURN_URL:-}
        - NEXT_PUBLIC_TURN_USER=${TURN_USER:-}
        - NEXT_PUBLIC_TURN_PASS=${TURN_PASS:-}
    ports:
      - 3991:80
    volumes:
      - ./src:/usr/share/nginx/html/out

  signal:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
