FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

ARG NEXT_PUBLIC_TURN_URL
ARG NEXT_PUBLIC_TURN_USER
ARG NEXT_PUBLIC_TURN_PASS

ENV NEXT_TELEMETRY_DISABLED 1
ENV NEXT_PUBLIC_TURN_URL=${NEXT_PUBLIC_TURN_URL}
ENV NEXT_PUBLIC_TURN_USER=${NEXT_PUBLIC_TURN_USER}
ENV NEXT_PUBLIC_TURN_PASS=${NEXT_PUBLIC_TURN_PASS}

RUN npm run build


FROM nginx:stable-alpine

COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 3991

ENTRYPOINT ["nginx", "-g", "daemon off;"]
